@+ from button import homekit_button +@
@+ from category_block import category_block +@
@+ from block_label import block_label +@
@+ from scene_button import scene_button +@

title: Westmin
views:
  - title: Home
    path: default_view
    panel: true
    badges: []
    cards:
      - type: custom:mod-card
        style:
          "ha-card > layout-card":
            $: >
              #columns > div.column.cards:first-child 
                {background: #464646; height: 100vh; padding: 0 15px 15px 15px;}
              #columns > div.column.cards:nth-child(2)
                {background:radial-gradient(ellipse at center, rgba(87,87,87,1) 0%,
                rgba(26,26,26,1) 100%); height: 100vh; padding: 0 15px 15px 15px;}
        card:
          type: custom:layout-card
          layout: horizontal
          min_columns: 2
          column_width: [25%, 75%]
          cards:
            - type: vertical-stack
              cards:
                @@include sidebar.yaml@@

            - type: custom:layout-card
              layout: grid
              gridcols: 1fr 1fr 1fr
              cards:
                - @%block_label("Kitchen")%@
                - @%block_label("Halls")%@
                - @%block_label("Outdoors")%@

                - @% category_block() %@
                    - @% homekit_button("Pendants",
                          "light.kitchen_pendants", "icons/pendant.svg") %@
                    - @% homekit_button("Pots",
                          "light.kitchen_pots", "icons/pot-light2.svg") %@
                    - @% homekit_button("Table",
                          "light.kitchen_table", "icons/pot-light2.svg") %@

                - @% category_block() %@
                    - @%homekit_button("Main",
                          "light.main_hall_pots", "icons/pot-light2.svg")%@
                    - @%homekit_button("Lower",
                          "light.basement_hall_stairs", "icons/pot-light2.svg")%@
                    - @%homekit_button("Utility Room",
                          "light.basement_utillity_room", "icons/pot-light2.svg")%@

                - @% category_block() %@
                    - @%homekit_button("Garage",
                          "light.outdoors_garage_pots", "icons/pot-light2.svg")%@
                    - @%homekit_button("Porch",
                          "light.outdoors_front_porch", "icons/pot-light2.svg")%@
                    - @%homekit_button("Lawn Lamp",
                          "light.outdoors_lawn_lamp", "icons/pot-light2.svg")%@
                    - @%homekit_button("Low Voltage",
                          "light.outdoors_low_volt_lights", "icons/pot-light2.svg")%@

                - @%block_label("Family Room")%@
                - @%block_label("Living Room")%@
                - @%block_label("Dining Room")%@

                - @% category_block() %@
                    - @% homekit_button("Pots", "light.family_room_pots",
                          "icons/pot-light2.svg", tap=False) %@
                      tap_action:
                        action: call-service
                        service: light.toggle
                        service_data:
                          entity_id: entity
                          brightness_pct: 50
                    - @% homekit_button("Christmas tree",
                          "light.family_room_christmas_tree") %@

                - @% category_block() %@
                    - @%homekit_button("Lamps",
                          "light.living_room_lamps", "icons/lr-lamp.svg") %@
                    - @%homekit_button("Pots",
                          "light.living_room_pot_lights", "icons/pot-light2.svg") %@

                - @% category_block() %@
                    - @% homekit_button("Chandelier",
                          "light.dining_room_chandelier", "icons/chandelier.svg") %@
                    - @% homekit_button("Pots",
                          "light.dining_room_pots", "icons/pot-light2.svg") %@

                - @% block_label("Scenes") %@
                - type: custom:gap-card
                - @% block_label("Security") %@

                - @% category_block() %@
                    - @% scene_button("Hygge", "scene.hygge") %@
                    - @% scene_button("Party", "scene.party") %@

                - type: custom:gap-card

                - @% category_block() %@
                    - @@include garage_door.yaml@@
